### ISSUE TITLE
Program loop work

### ISSUE THREAD

**Issue by Mobivlad** [taneko-ua/lab_LCD#2]
On pins, where buttons are connected there is a HIGH level without a button push.
![image](https://user-images.githubusercontent.com/17147322/77512709-41f81980-6e7c-11ea-9214-a9022a67458d.png)

https://github.com/taneko-ua/lab_LCD/blob/2611fb1c4210a93ae35bdf0dbb726e5fa1116181/Src/main.c#L107
https://github.com/taneko-ua/lab_LCD/blob/2611fb1c4210a93ae35bdf0dbb726e5fa1116181/Src/main.c#L113
https://github.com/taneko-ua/lab_LCD/blob/2611fb1c4210a93ae35bdf0dbb726e5fa1116181/Src/main.c#L119
https://github.com/taneko-ua/lab_LCD/blob/2611fb1c4210a93ae35bdf0dbb726e5fa1116181/Src/main.c#L125
https://github.com/taneko-ua/lab_LCD/blob/2611fb1c4210a93ae35bdf0dbb726e5fa1116181/Src/main.c#L131

**Comment by taneko-ua** [comment]
Fixed
